- name: Install filebeat version 7.x
  apt:
    deb: "{{ filebeat_download_url }}"
    state: present
  notify:
    - restart filebeat

- name: start and enable filebeat
  service:
    name: filebeat
    state: started
    enabled: true