- name: create filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: '{{ filebeat_config_path }}'
  notify:
    - restart filebeat

- name: copy ca certificate if required
  copy:
    content: "{{ filebeat_ca_cert }}"
    dest: "{{ filebeat_ca_path }}"
    owner: root
    group: root
    mode: 0400
  when: filebeat_ca_cert != None

- name: copy ssl certificate if required
  copy:
    content: "{{ filebeat_ssl_cert }}"
    dest: "{{ filebeat_ssl_cert_path }}"
    owner: root
    group: root
    mode: 0400
  when: filebeat_ssl_cert != None

- name: copy ssl key if required
  copy:
    content: "{{ filebeat_ssl_key }}"
    dest: "{{ filebeat_ssl_key_path }}"
    owner: root
    group: root
    mode: 0400
  when: filebeat_ssl_key != None