---
# Version 7 is split into oss version, we only support oss version for now and
# seems not be available in deb repo.
- fail:
    msg: 'Unsupported filebeat version'
  when: filebeat_version.split('.')[0] != '7' or filebeat_distribution|default('none') != 'oss'

- block:
  - include: redhat.yml
    when: ansible_os_family == 'RedHat'

  - include: debian.yml
    when: ansible_os_family == 'Debian'

  - include: windows.yml
    when: ansible_os_family == 'Windows'

- include_tasks: deploy-config.yml