- name: Download the filebeat zip archive
  win_get_url:
    url: '{{ filebeat_download_url }}'
    dest: '{{ ansible_install_dir }}\filebeat-{{ filebeat_distribution }}-{{ filebeat_version }}-windows.zip'

- set_fact:
    filebeat_config_dir: '{{ ansible_install_dir }}\filebeat-{{ filebeat_version }}-windows-x86_64'

- name: Extract filebeat archive
  win_command: '"C:\Program Files\7-Zip\7z.exe" x -y -o{{ ansible_install_dir }}\ {{ ansible_install_dir }}\filebeat-{{ filebeat_distribution }}-{{ filebeat_version }}-windows.zip'
  args:
    creates: '{{ filebeat_config_dir }}'

# These facts can be used in the dict filebeat_config that is used by the
# filebeat config template file deployed in the next task.
- set_fact:
    filebeat_ca_path: '{{ filebeat_config_dir }}\ca.crt'
    filebeat_ssl_cert_path: '{{ filebeat_config_dir }}\ssl.crt'
    filebeat_ssl_key_path: '{{ filebeat_config_dir }}\ssl.key'
    filebeat_config_path: '{{ filebeat_config_dir }}\filebeat.yml'

- include_tasks: deploy-config.yml

- name: Run the installer to install the service
  win_shell: '{{ filebeat_config_dir }}\install-service-filebeat.ps1'
  args:
    chdir: '{{ filebeat_config_dir }}'

- name: Enable filebeat service
  win_service:
    name: filebeat
    start_mode: auto
    state: restarted
