---
- name: restart filebeat
  service:
    name: filebeat
    state: restarted
  when: ansible_os_family != 'Windows'

- name: restart filebeat
  win_service:
    name: filebeat
    state: restarted
  when: ansible_os_family == 'Windows'